stages:
  - install
  - api-tests
  - web-tests
  - k6-tests

default:
  image: node:20
  before_script:
    - apt-get update && apt-get install -y curl unzip chromium
    - npm ci

install_dependencies:
  stage: install
  script:
    - echo "Installing project dependencies..."
  artifacts:
    paths:
      - node_modules/

api_tests:
  stage: api-tests
  dependencies: [install_dependencies]
  script:
    - echo "Running API tests with Vitest..."
    - npx vitest run

web_tests:
  stage: web-tests
  image: cypress/browsers:node-20.5.0-chrome-113
  dependencies: [install_dependencies]
  before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm ci
  script:
    - echo "Running WebdriverIO tests..."
    - npx wdio wdio.conf.js

k6_tests:
  stage: k6-tests
  image: grafana/k6
  script:
    - echo "Running k6 performance test..."
    - k6 run k6/test.js
